source 'https://cdn.cocoapods.org/'
source 'https://github.com/WZLYiOS/WZPodSpecs.git'

platform:ios, '13.0'
use_frameworks!

target 'WZNetwork_Example' do
  pod 'WZNetwork', :path => '../'
  pod 'WZEncryption', '~> 1.0.0'#加密组件
  pod 'WZUUID', '~> 2.0.0' #唯一标识
  pod 'CleanJSON', '~> 1.0.0' #动态处理JSON问题
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 13.0
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
  end
end
